data:
  dataloader: {batch_size: 36, class_balance: true, data_workers: 3}
  dataset: {n_share: [0,5], n_total: 10, name: digital, root_path: ~/Remote-Pycharm/ETN,
    source: 1, target: 0}
log: {log_interval: 10, root_dir: public}
misc: {gpus: 1}
model: {base_model: lenet,pretrained_model: None}
test: {resume_file: Clipart_to_Art.pkl, test_interval: 500, test_only: false}
train: {adv_loss_aug_tradeoff: 10.0, adv_loss_tradeoff: 1.0, ce_aug_tradeoff: 1.0,
  entropy_tradeoff: 0.2, lr: 0.001, min_step: 20000, momentum: 0.9, weight_decay: 0.0005}

